version: "3.8"
services:
  postgres-db:
    container_name: time-db
    image: "postgres" # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: time
      POSTGRES_PASSWORD: time
      POSTGRES_DB: time_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5442:5432"